### ISSUE TITLE
Green screen when using OBS version > 23.2.1

### ISSUE THREAD

**Issue by jkluch** [a-rose/obs-headless#2]
I wanted to use libobs for a personal project and used your project here as a reference/starting point so thanks.
I worked out why after v23.2.1 output is green.
This PR https://github.com/obsproject/obs-studio/pull/1978 is where the issue gets introduced..

If you set the below line to `video_gpu_conversion true` recording should output correctly..
https://github.com/a-rose/obs-headless/blob/54212c3a521b1954a0148d40d345c1a431be2e3c/config.txt#L8

I'll be honest I don't fully understand this but it looks like the effect files were handling color conversions in v23.2.1 and because that affected performance slightly it was removed from there.  I'm not sure if this change unintentionally removed compatibility with `gpu_conversion=false` or if maybe there's an additional thing that needs to be configured for `gpu_conversion=false` to work.. as far as I can tell the OBS application itself doesn't use `gpu_conversion=false` so maybe while it's a setting it's not really intended to be modified from `true`

**Comment by a-rose** [comment]
Many thanks for looking into this and sharing your findings ! 😄  I can't test this myself right now, but I agree with you ; the OBS app doesn't cover all cases implemented in the libs, so it's pretty likely the breaking change was never tester.
If you want to make a PR for this, I'll be happy to accept it. 😄

**Comment by a-rose** [comment]
Hello, this is fixed in v2.1.0. Finally :)
