### ISSUE TITLE
QT issue 

### ISSUE THREAD

**Issue by armpdq** [a-rose/obs-headless#3]
done exactly using the manual, buuuut: 
root@pull-test:/opt/obs-headless# ./run_server.sh
Current working directory (for core dumps etc): /root/obs-studio-portable//bin/64bit/
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

./run_server.sh: line 15: 13665 Aborted                 (core dumped) ${here}/build/obs_headless_server

any ideas?

**Comment by a-rose** [comment]
Hey,

I just pushed a branch that works with docker: https://github.com/a-rose/obs-headless/tree/docker
Would you consider trying this ? It should solve your issue.

If you're not willing to use Docker, try `ldd build/obs_headless_server` and see if there are missing libraries.
Here is the list of libs I install in Docker:
```
build-essential cmake git

libmbedtls-dev libasound2-dev libavcodec-dev libavdevice-dev
libavfilter-dev libavformat-dev libavutil-dev libcurl4-openssl-dev
libfdk-aac-dev libfontconfig-dev libfreetype6-dev libglvnd-dev
libjack-jackd2-dev libjansson-dev libluajit-5.1-dev libpulse-dev
libqt5x11extras5-dev libspeexdsp-dev libswresample-dev libswscale-dev
libudev-dev libv4l-dev libvlc-dev libwayland-dev libx11-dev
libx264-dev libxcb-shm0-dev libxcb-xinerama0-dev libxcomposite-dev
libxinerama-dev pkg-config python3-dev qtbase5-dev qtbase5-private-dev
libqt5svg5-dev swig libxcb-randr0-dev libxcb-xfixes0-dev
libx11-xcb-dev libxcb1-dev libxss-dev qtwayland5 libgles2-mesa
libgles2-mesa-dev

libgrpc++-dev libgrpc++1 libgrpc-dev libgrpc6
libprotobuf-dev protobuf-compiler-grpc
```

You probably need some libxcb libs.

**Comment by a-rose** [comment]
I merged my docker branch in master, this issue should be solved now.
