### ISSUE TITLE
Unable to start client

### ISSUE THREAD

**Issue by AgentScrubbles** [a-rose/obs-headless#7]
Hello and thank you for this project!  I'm diving in, and the code seems straightforward so far, but ran into this issue.  The server is up, I'm able to stream the source to the server, but when starting the client I receive these logs:

```bash
 ✔ Container obs-headless-client-1  Created                                                                                                                            0.1s 
Attaching to client-1
client-1  | client.cpp:441 Health() error Health failed: failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50051: Failed to connect to remote host: connect: Connection refused (111)	
client-1  | client.cpp:118 main() error An exception occured: 	exception=Health failed: failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50051: Failed to connect to remote host: connect: Connection refused (111) 
client-1  | client.cpp:127 main() trace Exit client
```

My docker compose ps looks like:
```bash
obs-headless-rtsp-1     aler9/rtsp-simple-server   "/mediamtx"   rtsp      6 minutes ago   Up 6 minutes   
obs-headless-server-1   obs-headless:latest        "/bin/bash"   server    6 minutes ago   Up 6 minutes  
```

I'm not exactly sure what the client is vs the server.  If I'm reading the docs right, the server is in charge of actually managing the streams, but I'm not sure where the client comes in. 

Trying to run `ffplay` directly results in:
```bash
ffplay rtmp://localhost/live/key
ffplay version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2003-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
rtmp://localhost/live/key: Input/output error 0KB sq=    0B f=0/0  
```

Maybe a networking error, can't connect to the stream? But then I can push to the stream (edit: but it the ffmpeg command keeps running even if the server is stopped, so maybe not).  I also see no logs of any kind coming out of the server, and I'm not sure if that's intentional.  Hopefully my issue is obvious to you!

**Comment by a-rose** [comment]
Hello, thanks for trying out the project!

I can't try to reproduce at the moment, I bought a new GPU and I could not make the NVidia drivers work with it yet 😅.

The docs are far from exhaustive at the moment, so I'll try to explain the architecture in a few words:

**Services**
- `obs-headless-server` is a stripped down OBS: it reads input sources and streams its output to the desired endpoint.
- `obs-headless-client` controls the server remotely. Its main role is to load a "show" file (`etc/shows/default.json`) and send commands to the server to make it create and manage the sources and scenes required to compose the show.
     - For example, when you run the client, you'll be able to switch from one source to another by pressing a key.
     - The provided client is meant as an example implementation. I was reworking the project to extract the client from the server code, but this is paused due to my GPU problems.

The services below are placeholders for development, you might not need them if you want to use other sources and output endpoint.
- `obs-headless-rtsp` is used as an input media server (relaying the input test sources) and as an output media server (receiving obs-server-headless' output).
- `sourceA` and `sourceB` stream video test sources to act as live content.


![Screenshot 2024-11-06 at 11 22 52](https://github.com/user-attachments/assets/9ed0879a-3936-4583-ad16-9eefb0c8fbd9)

**Config**
- The input sources are set the default show in `etc/shows/default.json`
- The output endpoint is set as `server` + `key` in `etc/config.txt`



----------------

Back to the issue you are encountering.

I think this is due to a problem with the server's entrypoint. If you are using `master`, can you try with `dev` please? There are a few commits that I did not merge yet, and one fixes the missing entrypoint.

Also, it looks like you are not running the test sources. If you did not edit the default show, you will only see a black screen. 
Did you run `make generate` before ``make up`?

**Comment by AgentScrubbles** [comment]
That's it! It's working!   This is PHENOMENAL work!  Thank you for the diagram, it explained a lot!  Light feedback, maybe add it to the README or STREAMING.md, if you don't know in github you can add the image to the repo anywhere and then display it with the syntax `![alt text](./path/to/image.jpg)` (relative to your repo.

I'm working on setting up a way to have a  co-hosted twitch stream where my friend and I can both jump on at any point and this is exactly what I needed to get started!

**Comment by a-rose** [comment]
Awesome! 

I need to work on docs more, yes.

**Comment by AgentScrubbles** [comment]
I'm really sorry to re-open this, but I have one more question.  What is the schema for the JSON in the shows, or where were you able to pull it from? I cannot for the life of me find where the schema is.  I'm trying to run two sources, just simply side by side, and I can't figure out how to do that.  What I currently have is:

```json
{
      "name": "Big Show",
      "scenes": [
          {
              "name": "scene_0",
              "sources": [
                  {
                      "name": "Single",
                      "type": "RTMP",
                      "url": "rtmp://localhost/sourceA"
                  }
              ]
          },
          {
              "name": "scene_1",
              "sources": [
                  {
                      "name": "Left",
                      "type": "RTMP",
                      "url": "rtmp://localhost/sourceA",
                      "x": 0,
                      "y": 0
                  },
                  {
                      "name": "Right",
                      "type": "RTMP",
                      "url": "rtmp://localhost/sourceB",
                      "width": 1280,
                      "height": 720,
                      "pos": {
                          "x": 1280.0,
                          "y": 0.0
                      },
                      "scale": {
                          "x": 0.66666668653488159,
                          "y": 0.66666668653488159
                      },
                      "align": 5
                  }
              ]
          }
      ]
    }
```
    
No matter what I try, "pos", "position", just "x" and "y", it overlays one on top of the other.  I know this is out of scope of your project, but I'm hoping you can show me where you learned the schema from.  Thank you

**Comment by a-rose** [comment]
There is no spec for the json show files at the moment. When I started working on this project again, this was going to be the next big step, but I ended up working for months on updating the base Docker images and OBS versions instead, yikes.

There's an example of a scene with two sources here: https://github.com/a-rose/obs-headless/blob/master/etc/shows/bigshow.json. You can set width and height but I didn't implement x/y placement yet... so there is no way to make them not overlap at the moment :(

**Comment by AgentScrubbles** [comment]
Would that be something you would be open to implement in the next 2 weeks? I have a partial solution for my personal stream that I cobbled together with ffmpeg, but it's not elegant.   I dove into the cpp code a bit, but it's been well over a decade since I did cpp, and setting up the environment alone would be a lot for me.  I'd be happy to sponsor you here for the work done, I'm also an engineer and I know it's not free.  If you could implement x,y so I could have two streams, side by side, that would be incredibly helpful to me.  You can email me directly at public.postal286@passinbox.com, we can work out details.

**Comment by a-rose** [comment]
I would love to do something like that :)
I won't have time to fix my setup this week unfortunately. But if I do manage to fix it next week, I'll send you an email and we can work things out going forward.
